### ISSUE TITLE
jade-spark didn't compile

### ISSUE THREAD

**Issue by fipo** [ldaidone/jade-spark#1]
Hey guys, 

I have a some kind of error here.

So I have this basic structure of my CI 2.2
| application
| public
| sparks
| -- jade-spark
...

currently jade-spark.php is loaded but I have a problem w/ .jade rendering

``` command:
'/usr/local/bin/jade' < '../application/views/welcome.jade' --path ../application/views/d --obj '{"first_name":"Leo","other_name":"Burnett"}'
params:'{
    "first_name": "Leo",
    "other_name": "Burnett"
}'
Issue:
probably file not found(please check if file '../application/views/welcome.jade' exists)
```

So I'm completely sure that file is exist ;)
Also I tried  several different setups of `$config['jade_tpl_path']` but noting helped.

Also tried to execute this form my console and works perfectly 
https://www.evernote.com/shard/s77/sh/5a1a4e6f-4bcb-4c40-9795-dfd43cf9711b/07899412d5424985469b244ccefdea5e

Any idea ... !?

**Comment by ldaidone** [comment]
Hi Fipo,

Sorry for the delay, after some tests I was able to reproduce this error. 
I've been working on a better error handling messages, since the problem wasn't the template existences, but the binary wasn't able to execute.

I'll be pushing those fixes this week, but in the meantime, you can change in your config file 

`$config['jade_bin'] = "/usr/local/bin/node /usr/local/bin/jade";`

It worked for me, if it doesn't work for your, don't hesitate to ping.

Regards,

Leo.
